site_name: Microbial Outbreak Surveillance System
site_url: https://example.com/
nav:
    - Home: index.md
    - Installation: installation.md
    - About: about.md
    - Citation: citation.md


theme: readthedocs